/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IChainlinkDataStreamVerifier,
  IChainlinkDataStreamVerifierInterface,
} from "../../../contracts/oracle/IChainlinkDataStreamVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "payload",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "parameterPayload",
        type: "bytes",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bytes",
        name: "verifierResponse",
        type: "bytes",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IChainlinkDataStreamVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IChainlinkDataStreamVerifierInterface {
    return new utils.Interface(_abi) as IChainlinkDataStreamVerifierInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IChainlinkDataStreamVerifier {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IChainlinkDataStreamVerifier;
  }
}
